### ISSUE TITLE
大佬最新版的bug会修改吗？

### ISSUE THREAD

**Issue by 0nion1** [winezer0/burp-wildcard#1]
大佬你好，我测试burp版本 2022.3.6 加载插件并启用后无法返回burp原来的标签了（比如proxy），只能在插件的标签跳转

**Comment by winezer0** [comment]
能截图描述一下吗？和readme上的bug一样吗

**Comment by 0nion1** [comment]
是的，开启插件后点击插件那栏可以跳转过去，点击第一栏burp自带的功能点了之后就没有反应，也跳转不过去。
<img width="1620" alt="image" src="https://user-images.githubusercontent.com/53221874/180215471-707569ab-5d56-4c71-93c0-a55d7a709703.png">

**Comment by winezer0** [comment]
已尝试进行修复
